# Generated by Django 5.1a1 on 2024-05-27 01:45

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    initial = True

    dependencies: list[tuple[str, str]] = []

    operations: list[Operation] = [
        migrations.CreateModel(
            name="WebhallenProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="The date and time the product was created."),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, help_text="The date and time the product was last modified."),
                ),
                (
                    "product_id",
                    models.IntegerField(db_index=True, help_text="The product id of the product.", unique=True),
                ),
                ("name", models.CharField(help_text="The name of the product.", max_length=255)),
                ("price", models.DecimalField(decimal_places=2, help_text="The price of the product.", max_digits=10)),
                ("url", models.URLField(help_text="The URL of the product.")),
                ("image_url", models.URLField(help_text="The URL of the product image.")),
            ],
            options={
                "verbose_name": "Webhallen Product",
                "verbose_name_plural": "Webhallen Products",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
                "base_manager_name": "prefetch_manager",
                "indexes": [
                    models.Index(fields=["created_at"], name="webhallen_w_created_7946a6_idx"),
                    models.Index(fields=["modified_at"], name="webhallen_w_modifie_093523_idx"),
                    models.Index(fields=["name"], name="webhallen_w_name_01ba99_idx"),
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="WebhallenJSON",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="The date and time the JSON was first scraped."),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, help_text="The date and time the JSON was last modified."),
                ),
                ("scraped_url", models.URLField(help_text="The URL from which the JSON was scraped.", unique=True)),
                (
                    "json",
                    models.JSONField(blank=True, help_text="The JSON data scraped from the webhallen API.", null=True),
                ),
                (
                    "product",
                    auto_prefetch.ForeignKey(
                        help_text="The product associated with the JSON.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jsons",
                        to="webhallen.webhallenproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhallen JSON",
                "verbose_name_plural": "Webhallen JSONs",
                "ordering": ["-created_at"],
                "get_latest_by": "-created_at",
                "abstract": False,
                "base_manager_name": "prefetch_manager",
                "indexes": [
                    models.Index(fields=["created_at"], name="webhallen_w_created_43ebb4_idx"),
                    models.Index(fields=["modified_at"], name="webhallen_w_modifie_20966f_idx"),
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
