# Generated by Django 5.1.1 on 2024-10-03 22:24
from __future__ import annotations

from typing import TYPE_CHECKING, ClassVar

from django.db import migrations, models

if TYPE_CHECKING:
    from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    """Initial migration for the Webhallen app."""

    initial = True

    dependencies: ClassVar[list[tuple[str, str]]] = []

    operations: ClassVar[list[Operation]] = [
        migrations.CreateModel(
            name="SitemapArticle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sitemap", models.TextField(help_text="The sitemap XML")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When the data was fetched")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="When the data was last updated")),
            ],
            options={
                "verbose_name": "Webhallen Sitemap - article",
                "verbose_name_plural": "Webhallen Sitemap - article",
            },
        ),
        migrations.CreateModel(
            name="SitemapCampaign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sitemap", models.TextField(help_text="The sitemap XML")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When the data was fetched")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="When the data was last updated")),
            ],
            options={
                "verbose_name": "Webhallen Sitemap - campaign",
                "verbose_name_plural": "Webhallen Sitemap - campaign",
            },
        ),
        migrations.CreateModel(
            name="SitemapCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sitemap", models.TextField(help_text="The sitemap XML")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When the data was fetched")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="When the data was last updated")),
            ],
            options={
                "verbose_name": "Webhallen Sitemap - category",
                "verbose_name_plural": "Webhallen Sitemap - category",
            },
        ),
        migrations.CreateModel(
            name="SitemapHome",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sitemap", models.TextField(help_text="The sitemap XML")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When the data was fetched")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="When the data was last updated")),
            ],
            options={
                "verbose_name": "Webhallen Sitemap - home",
                "verbose_name_plural": "Webhallen Sitemap - home",
            },
        ),
        migrations.CreateModel(
            name="SitemapInfoPages",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sitemap", models.TextField(help_text="The sitemap XML")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When the data was fetched")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="When the data was last updated")),
            ],
            options={
                "verbose_name": "Webhallen Sitemap - info pages",
                "verbose_name_plural": "Webhallen Sitemap - info pages",
            },
        ),
        migrations.CreateModel(
            name="SitemapManufacturer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sitemap", models.TextField(help_text="The sitemap XML")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When the data was fetched")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="When the data was last updated")),
            ],
            options={
                "verbose_name": "Webhallen Sitemap - manufacturer",
                "verbose_name_plural": "Webhallen Sitemap - manufacturer",
            },
        ),
        migrations.CreateModel(
            name="SitemapProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sitemap", models.TextField(help_text="The sitemap XML")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When the data was fetched")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="When the data was last updated")),
            ],
            options={
                "verbose_name": "Webhallen Sitemap - product",
                "verbose_name_plural": "Webhallen Sitemap - product",
            },
        ),
        migrations.CreateModel(
            name="SitemapSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sitemap", models.TextField(help_text="The sitemap XML")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When the data was fetched")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="When the data was last updated")),
            ],
            options={
                "verbose_name": "Webhallen Sitemap - section",
                "verbose_name_plural": "Webhallen Sitemap - section",
            },
        ),
        migrations.CreateModel(
            name="WebhallenProductJSON",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("webhallen_id", models.PositiveIntegerField(help_text="Webhallen product ID", unique=True)),
                ("data", models.JSONField(help_text="JSON data from Webhallen API")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When the data was fetched")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="When the data was last updated")),
            ],
            options={
                "verbose_name": "Webhallen data",
                "verbose_name_plural": "Webhallen data",
            },
        ),
    ]
