# Generated by Django 5.1a1 on 2024-05-27 03:31

from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: list[tuple[str, str]] = [
        ("webhallen", "0001_initial"),
    ]

    operations: list[Operation] = [
        migrations.RemoveField(
            model_name="webhallenproduct",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="webhallenproduct",
            name="price",
        ),
        migrations.AddField(
            model_name="webhallenproduct",
            name="last_exception",
            field=models.TextField(
                blank=True,
                help_text="The last exception that occurred when scraping the product.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="webhallenproduct",
            name="last_scraped_json_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The date and time the product was last scraped from the webhallen API.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="webhallenproduct",
            name="name",
            field=models.TextField(blank=True, help_text="Product name.", null=True),
        ),
        migrations.AlterField(
            model_name="webhallenproduct",
            name="product_id",
            field=models.IntegerField(db_index=True, help_text="Product id", unique=True),
        ),
    ]
