# Generated by Django 5.1.1 on 2024-10-04 21:01
from __future__ import annotations

from typing import TYPE_CHECKING, ClassVar

from django.db import migrations, models

if TYPE_CHECKING:
    from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    """Allow WebhallenProductJSON.data field to be null."""

    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("webhallen", "0001_initial"),
    ]

    operations: ClassVar[list[Operation]] = [
        migrations.AlterField(
            model_name="webhallenproductjson",
            name="data",
            field=models.JSONField(help_text="JSON data from Webhallen API", null=True),
        ),
    ]
