version: '3.9'

services:
  postgres:
    image: ghcr.io/thelovinator1/panso_postgres:latest
    container_name: panso_postgres
    ports:
      - 5432:5432
    volumes:
      - /Docker/Panso/Postgres/data:/var/lib/postgresql/data
      - /Docker/Panso/Postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?error}
      - POSTGRES_USER=panso
      - POSTGRES_DB=panso
    restart: always
