# Generated by Django 5.0.3 on 2024-03-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhallenJSON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Flag to indicate if the JSON is still available for use.')),
                ('product_id', models.IntegerField(db_index=True, help_text='The product id of the product.', unique=True)),
                ('scraped_url', models.URLField(help_text='The URL from which the JSON was scraped.', unique=True)),
                ('json', models.JSONField(blank=True, help_text='The JSON data scraped from the webhallen API.', null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], default='success', help_text='Status of the scraping process', max_length=10)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message if the scraping process encountered an issue')),
            ],
            options={
                'verbose_name': 'Webhallen JSON',
                'verbose_name_plural': 'Webhallen JSONs',
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.AddConstraint(
            model_name='webhallenjson',
            constraint=models.CheckConstraint(check=models.Q(('product_id__gte', 0)), name='product_id_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='webhallenjson',
            constraint=models.CheckConstraint(check=models.Q(('scraped_url__startswith', 'https://www.webhallen.com/api/product/')), name='scraped_url_starts_with_https_www_webhallen_com_api_product_'),
        ),
    ]
