# Generated by Django 5.0.3 on 2024-03-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhallenjson',
            name='status',
        ),
        migrations.AlterField(
            model_name='webhallenjson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time the JSON was first scraped.'),
        ),
        migrations.AlterField(
            model_name='webhallenjson',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time the JSON was last modified.'),
        ),
    ]
