# Generated by Django 5.0.3 on 2024-03-13 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panso', '0002_remove_webhallenjson_status_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='webhallenjson',
            name='product_id_not_negative',
        ),
        migrations.RemoveConstraint(
            model_name='webhallenjson',
            name='scraped_url_starts_with_https_www_webhallen_com_api_product_',
        ),
    ]
