name: Build and Push Docker Image

on:
  push:
    paths:
      - "Docker/**"
      - ".github/workflows/docker-build-and-push.yml"
  pull_request:
  schedule:
    - cron: "0 0 * * *" # Run every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 \
            -f Docker/PansoPostgres.Dockerfile \
            -t ghcr.io/${{ github.repository }}/panso_postgres:latest \
            --push .
